---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install mc
  apt:
    name: mc
    update_cache: yes
    state: latest

- name: Install net-tools 
  apt:
    name: net-tools
    update_cache: yes
    state: latest

- name: Install jre
  apt:
    name: default-jre 
    update_cache: yes
    state: latest
