apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  labels:
    app: k8s-app
spec:
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
        - name: py-webpage
          image: pydevlab/py-page:latest
          ports:
            - containerPort: 8000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-deployment
  minReplicas: 3
  maxReplicas: 5

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-service
  labels:
    app: k8s-app
spec:
  type: LoadBalancer
  selector:
    app: k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
